export const styles = {
  havaDurumu: {
    height: "300px",
    width: "100%",
    position: "absolute",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
  },
  havaIcon: {
    backgroundColor: "#f0f8fa",
    height: "70%",
    width: "100%",
    position: "absolute",
    textAlign: "center",
    left: 0,
    top: 10,
  },
  havaIconBefore: {
    display: "block",
    content: '"\f002"',
    color: "#818b8d",
    fontFamily: "weathericons",
    fontSize: "110px",
    position: "absolute",
    left: "50%",
    top: "58%",
    transform: "translate(-50%, -50%)",
  },
  havaBilgi: {
    backgroundColor: "#2e3336",
    height: "30%",
    width: "100%",
    position: "absolute",
    left: 0,
    bottom: 0,
  },
  havaDerece: {
    color: "#c5cdcf",
    fontFamily: "Open Sans",
    fontWeight: 200,
    fontSize: "2.9375em",
    lineHeight: "2.9375em",
    position: "absolute",
    left: "6%",
    top: "50%",
    transform: "translate(0, -50%)",
  },
  havaDurum: {
    color: "#8f9b9d",
    fontFamily: "Open Sans",
    fontWeight: 200,
    fontSize: "1.1875em",
    lineHeight: "1.1875em",
    position: "absolute",
    top: "24%",
    left: "27%",
  },
  havaSehir: {
    color: "#c5cdcf",
    fontFamily: "Open Sans",
    fontWeight: 400,
    fontSize: "0.8125em",
    lineHeight: "0.8125em",
    position: "absolute",
    bottom: "25%",
    left: "27%",
  },
  havaAy: {
    color: "#fff",
    fontFamily: "Open Sans",
    fontWeight: 700,
    textTransform: "uppercase",
    fontSize: "0.6875em",
    lineHeight: "0.6875em",
    position: "absolute",
    top: "30%",
    left: "50%",
    transform: "translate(-50%, 0)",
  },
  havaGun: {
    color: "#fff",
    fontFamily: "Open Sans",
    fontWeight: 500,
    fontSize: "1.8125em",
    lineHeight: "28px",
    position: "absolute",
    bottom: "24%",
    left: "50%",
    transform: "translate(-50%, 0)",
  },
  havaTarih: {
    backgroundColor: "#e9573f",
    height: "30%",
    width: "22%",
    position: "absolute",
    right: 0,
    bottom: 0,
  },
};
